[project]
name = "wekeo_combined_chain"
version = "0.3.0"
description = ""
requires-python = ">= 3.10"
authors = [{name = "HYGEOS", email = "contact@hygeos.com"}]
dependencies = [
    "xarray"
]

[project.optional-dependencies]
git = [
    # insert github dependencies
    "wekeo-frp-l3[git] @ git+https://github.com/hygeos/wekeo_frp_l3", 
    "wekeo-iasi-l3[git] @ git+https://github.com/hygeos/wekeo_iasi_l3", 
    "wekeo-s5p-pca-l3[git] @ git+https://github.com/hygeos/wekeo_s5p_pca_l3", 
    "wekeo_plumes_post_process[git] @ git+https://github.com/hygeos/wekeo_plumes_post_process"
]

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = {find = {}}

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
wekeo_combined_chain = { path = ".", editable = true, extras = ["git"] }


[tool.pixi.tasks]
tests = "pytest tests/"


[tool.pixi.dependencies]
ipykernel = "*"
pytest = "*"
pytest-html = "*"
matplotlib-base = "*"
pytest-xdist = "*"
xarray = "*"
coda = "*"
dask = "*"

[tool.pixi.environments]
default = { features = ['sys', 'sub', 'dev'], solve-group = "default" }

[tool.pixi.feature.sys.dependencies]

[tool.pixi.feature.dev.dependencies]

[tool.pixi.feature.sub.dependencies]
xarray = "*"
cartopy = "*"
netcdf4 = "*"
numpy = "*"
